REQUEST_TIMEOUT_SECONDS = 20
MAX_LINKS_PER_SEED_PAGE = 120
MAX_PAGES_PER_DOMAIN = 25

RELEVANT_KEYWORDS = [
    "airport",
    "airports",
    "aerodrome",
    "aerodromes",
    "aviation",
    "civil aviation",
    "runway",
    "runways",
    "airfield",
    "infrastructure",
    "modernization",
    "rehabilitation",
    "operations",
    "night operations",
    "safety",
    "master plan",
    "procurement",
    "tender",
    "projects",
    "project",
    "expansion",
    "operator",
    "operators",
    "regional airport",
    "municipal airport",
    "airport development",
    "airport upgrade",
]

NEGATIVE_KEYWORDS = [
    "tourism",
    "travel guide",
    "trip",
    "vacation",
    "hotel",
    "restaurant",
    "shopping",
    "retail",
    "visa",
    "tripadvisor",
    "booking",
    "wikipedia",
    "culture",
    "must visit",
]
